-- 0010: every indicator, with its plain-language explainer.
--
-- Phase 1 (FRED) and Phase 2 (EIA, PortWatch, NOAA/NSIDC, FAO, USBR) in one
-- place. Adding an indicator to a source that already has a connector is an
-- insert here and nothing else: the connector reads source_series_id and
-- transform and derives the rest.
--
--   transform 'ratio'   -> source_series_id is "NUMERATOR/DENOMINATOR"
--   transform 'derived' -> the connector computes it; see source_series_id
--   seasonal = true     -> compared against the same time of year
--
-- Generated from the live table so it cannot drift from what ships.

begin;

insert into indicators (
  slug, name, failure_mode, source, source_series_id, unit, cadence, higher_is_worse, transform, is_counter, seasonal, stale_after_days, explainer, notes, source_url, license, display_order
) values
  ('hy_oas', 'High Yield OAS', 'credit_plumbing', 'fred', 'BAMLH0A0HYM2', 'pp', 'daily', true, 'level', false, false, 5, 'The extra interest that financially shaky companies must pay to borrow, compared with the US government. It is the market''s live judgement on how likely those companies are to fail. It moves fast and it moves first, which makes it usually the earliest visible sign that credit is tightening.', 'ICE BofA US High Yield option-adjusted spread. The fastest-moving credit stress gauge on the board.', 'https://fred.stlouisfed.org/series/BAMLH0A0HYM2', 'ICE Data Indices, LLC - used with permission via FRED; check the series page before redistributing.', 10),

  ('ig_oas', 'Investment Grade OAS', 'credit_plumbing', 'fred', 'BAMLC0A0CM', 'pp', 'daily', true, 'level', false, false, 5, 'The same extra borrowing cost, but for large, financially solid companies - the ones that are supposed to be safe. When their borrowing costs widen, stress has spread from the risky edge of the market into its core.', 'ICE BofA US Corporate option-adjusted spread. Widening here means stress has reached balance sheets that are supposed to be safe.', 'https://fred.stlouisfed.org/series/BAMLC0A0CM', 'ICE Data Indices, LLC - used with permission via FRED; check the series page before redistributing.', 20),

  ('bank_reserves', 'Bank Reserve Balances', 'credit_plumbing', 'fred', 'WRESBAL', '$M', 'weekly', false, 'level', false, false, 12, 'Cash that commercial banks keep parked at the Federal Reserve. It is the buffer that lets banks settle payments with each other smoothly. Drain it too low and the plumbing of the financial system starts to seize - which is precisely what happened in September 2019.', 'Reserves held at the Fed. Draining reserves is where funding markets seize, so the sign is flipped: positive z means scarcer.', 'https://fred.stlouisfed.org/series/WRESBAL', 'Board of Governors of the Federal Reserve System; public domain via FRED.', 30),

  ('cc_delinq', 'Credit Card Delinquency Rate', 'credit_plumbing', 'fred', 'DRCCLACBS', '%', 'quarterly', true, 'level', false, false, 140, 'The share of credit card balances where the borrower has fallen behind on payments. A direct read on household financial stress, and one that lands on bank balance sheets as it worsens.', 'All commercial banks. Household stress showing up on bank books.', 'https://fred.stlouisfed.org/series/DRCCLACBS', 'Board of Governors of the Federal Reserve System; public domain via FRED.', 40),

  ('unemployment', 'Unemployment Rate', 'credit_plumbing', 'fred', 'UNRATE', '%', 'monthly', true, 'level', false, false, 45, 'The share of people who want a job and cannot find one. It reacts late - by the time it rises noticeably a downturn is usually well under way - but it is the number everything else is ultimately measured against.', 'U-3. Lagging, but the level everything else is indexed against.', 'https://fred.stlouisfed.org/series/UNRATE', 'U.S. Bureau of Labor Statistics; public domain via FRED.', 50),

  ('real_gdp_yoy', 'Real GDP Growth', 'credit_plumbing', 'fred', 'GDPC1', '% YoY', 'quarterly', false, 'yoy_pct', false, false, 140, 'How much bigger the economy is than it was a year ago, after stripping out inflation. The broadest single measure of whether things are growing or shrinking.', 'Year-over-year change in real GDP, derived from the level series. Sign flipped: positive z means slower growth.', 'https://fred.stlouisfed.org/series/GDPC1', 'U.S. Bureau of Economic Analysis; public domain via FRED.', 60),

  ('t5yifr', '5y5y Forward Inflation Expectation', 'fiscal_monetary', 'fred', 'T5YIFR', '%', 'daily', true, 'level', false, false, 5, 'What investors are betting inflation will average over a five-year stretch that starts five years from now. It is deliberately far off in the future, which strips out today''s noise and leaves a clean read on whether markets still believe the central bank will keep prices under control. Drifting upward means that belief is quietly eroding.', 'Market-implied inflation five years out, five years forward. The cleanest read on whether the central bank is still believed.', 'https://fred.stlouisfed.org/series/T5YIFR', 'U.S. Government public domain via FRED.', 10),

  ('t10y_yield', '10-Year Treasury Yield', 'fiscal_monetary', 'fred', 'DGS10', '%', 'daily', true, 'level', false, false, 5, 'The interest rate the US government pays to borrow money for ten years. It is the reference price for almost every other loan on earth - mortgages, company debt, other countries'' borrowing. When it climbs, financing everything gets more expensive.', 'Nominal cost of ten-year sovereign borrowing.', 'https://fred.stlouisfed.org/series/DGS10', 'U.S. Government public domain via FRED.', 20),

  ('t10y2y', '10y-2y Term Spread', 'fiscal_monetary', 'fred', 'T10Y2Y', 'pp', 'daily', false, 'level', false, false, 5, 'The gap between what the government pays to borrow for ten years and for two years. Normally, lending for longer earns more. When that gap shrinks or flips negative, investors are signalling they expect trouble ahead - historically one of the more reliable recession warnings there is.', 'Inversion (a low or negative spread) is the stress signal, so the sign is flipped: positive z means flatter or inverted.', 'https://fred.stlouisfed.org/series/T10Y2Y', 'U.S. Government public domain via FRED.', 30),

  ('sticky_cpi', 'Sticky-Price Core CPI', 'fiscal_monetary', 'fred', 'CORESTICKM159SFRBATL', '% YoY', 'monthly', true, 'level', false, false, 45, 'Inflation measured using only the prices that change slowly - rent, insurance, restaurant meals. Petrol prices bounce around weekly and tell you little about the trend; these do not move unless something real has shifted, and when they do move it tends to stick.', 'Atlanta Fed. Prices that reprice slowly, so a move here is harder to reverse than a headline print.', 'https://fred.stlouisfed.org/series/CORESTICKM159SFRBATL', 'Federal Reserve Bank of Atlanta; public domain via FRED.', 40),

  ('trimmed_pce', 'Trimmed Mean PCE Inflation', 'fiscal_monetary', 'fred', 'PCETRIM12M159SFRBDAL', '% YoY', 'monthly', true, 'level', false, false, 45, 'Inflation with the most extreme price moves in both directions thrown out, leaving the middle of the pack. It shows the underlying trend without one crashing or spiking category dominating the headline number.', 'Dallas Fed. Trims the tails rather than dropping fixed categories.', 'https://fred.stlouisfed.org/series/PCETRIM12M159SFRBDAL', 'Federal Reserve Bank of Dallas; public domain via FRED.', 50),

  ('net_interest_receipts', 'Federal Interest / Tax Receipts', 'fiscal_monetary', 'fred', 'A091RC1Q027SBEA/W006RC1Q027SBEA', 'ratio', 'quarterly', true, 'ratio', false, false, 140, 'How much of the government''s tax revenue is swallowed by interest on debt it already owes. Think of it as the share of a paycheck going to the minimum payment on a credit card: the higher it climbs, the less room there is for anything else, and the harder it is to borrow through the next emergency.', 'Federal interest payments divided by federal current tax receipts. Derived from two BEA series; the denominator is tax receipts specifically, not total receipts.', 'https://fred.stlouisfed.org/series/A091RC1Q027SBEA', 'U.S. Bureau of Economic Analysis; public domain via FRED.', 60),

  ('term_premium', '10-Year Term Premium', 'fiscal_monetary', 'fred', 'THREEFYTP10', '%', 'daily', true, 'level', false, false, 14, 'The extra yield investors demand purely for the risk of lending for ten years rather than rolling over short loans. Strip out expectations about future interest rates and this is what is left: the price of uncertainty about the distant future. When it rises, lenders are charging more simply for not knowing.', 'New York Fed ACM model, published via FRED.', 'https://fred.stlouisfed.org/series/THREEFYTP10', 'Federal Reserve Bank of New York; public domain via FRED.', 70),

  ('policy_uncertainty', 'Economic Policy Uncertainty', 'institutional', 'fred', 'USEPUINDXD', 'index', 'daily', true, 'level', false, false, 10, 'How often major newspapers are writing about uncertainty in government economic policy. It is an indirect measure, but a well-tested one: when businesses cannot predict tax, spending or trade rules, they postpone hiring and investment even while everything else looks fine.', 'Baker, Bloom and Davis index. A text-based proxy, not a direct measurement.', 'https://fred.stlouisfed.org/series/USEPUINDXD', 'Economic Policy Uncertainty (Baker/Bloom/Davis); free for non-commercial use, via FRED.', 10),

  ('equity_uncertainty', 'Equity Market Uncertainty', 'institutional', 'fred', 'WLEMUINDXD', 'index', 'daily', true, 'level', false, false, 10, 'The same newspaper-based method, narrowed to uncertainty that markets are actually reacting to. Read alongside the broader policy measure: when both climb together, the confusion has moved from opinion pages into prices.', 'Shares a methodology and authors with policy_uncertainty, so the two are correlated and this bucket is effectively one signal measured twice.', 'https://fred.stlouisfed.org/series/WLEMUINDXD', 'Economic Policy Uncertainty (Baker/Bloom/Davis); free for non-commercial use, via FRED.', 20),

  ('real_median_income', 'Real Median Household Income', 'institutional', 'fred', 'MEHOINUSA672N', '2024 $', 'annual', false, 'level', true, false, 550, 'What a typical household actually earns, adjusted for inflation. It uses the household exactly in the middle rather than the average, so a small number of very rich households cannot drag the figure upward.', 'Census, inflation-adjusted. Annual with a long release lag, so it is stale by construction.', 'https://fred.stlouisfed.org/series/MEHOINUSA672N', 'U.S. Census Bureau; public domain via FRED.', 20),

  ('labor_participation_prime', 'Prime-Age Labor Participation', 'institutional', 'fred', 'LNS11300060', '%', 'monthly', false, 'level', true, false, 45, 'The share of people aged 25 to 54 who are working or looking for work. That age band is chosen on purpose: it leaves out students and retirees, so it reflects whether people in their prime working years can find a place in the economy at all.', 'Ages 25-54, which strips out demographics and schooling decisions.', 'https://fred.stlouisfed.org/series/LNS11300060', 'U.S. Bureau of Labor Statistics; public domain via FRED.', 30),

  ('diesel_crack', 'Diesel Crack Spread', 'physical_resource', 'eia', 'derived:diesel_crack', '$/bbl', 'daily', true, 'derived', false, false, 10, 'The profit margin refiners make turning a barrel of crude oil into diesel. It is not published anywhere - it is computed here as the diesel price times 42 gallons, minus the crude price. It matters because when it widens, the squeeze is in refining capacity rather than in oil itself, which is a different and usually more stubborn problem.', 'Derived from NY Harbor ULSD spot and WTI Cushing spot. Only dates where both prices exist are used; nothing is carried forward.', 'https://www.eia.gov/dnav/pet/pet_pri_spt_s1_d.htm', 'U.S. Energy Information Administration; public domain.', 10),

  ('co2_per_gdp', 'CO2 per Unit of Real GDP', 'physical_resource', 'fred', 'EMISSCO2TOTVTTTOUSA/GDPC1', 'Mt CO2 / $B 2017', 'annual', true, 'ratio', true, false, 550, 'How much carbon dioxide is emitted per dollar of economic output. Falling means the economy is producing more while emitting less. It sits here as a deliberate counterweight: not every trend on this board is heading the wrong way.', 'Total US CO2 emissions divided by annualized real GDP. The EIA emissions series is discontinued upstream (last observation 2021), so this will always render heavily stale until a replacement feed is wired up.', 'https://fred.stlouisfed.org/series/EMISSCO2TOTVTTTOUSA', 'U.S. Energy Information Administration; public domain via FRED.', 10),

  ('diesel_retail', 'Retail Diesel Price', 'physical_resource', 'eia', 'petroleum/pri/gnd:EMD_EPD2D_PTE_NUS_DPG', '$/gal', 'weekly', true, 'level', false, false, 14, 'The average US price at the pump for diesel. Diesel moves freight - trucks, trains, ships, farm machinery - so when it rises, the cost of moving everything else rises with it, and that shows up in prices weeks later.', null, 'https://www.eia.gov/petroleum/gasdiesel/', 'U.S. Energy Information Administration; public domain.', 20),

  ('spr_level', 'Strategic Petroleum Reserve', 'physical_resource', 'eia', 'petroleum/stoc/wstk:WCSSTUS1', 'thousand bbl', 'weekly', false, 'level', false, false, 14, 'The United States'' emergency oil stockpile, held in underground salt caverns on the Gulf Coast. It exists to cover a sudden supply shock. The lower it runs, the less cushion there is if something breaks - so here, less is worse.', null, 'https://www.eia.gov/dnav/pet/pet_stoc_wstk_dcu_nus_w.htm', 'U.S. Energy Information Administration; public domain.', 30),

  ('crude_stocks', 'Commercial Crude Stocks', 'physical_resource', 'eia', 'petroleum/stoc/wstk:WCESTUS1', 'thousand bbl', 'weekly', false, 'level', false, true, 14, 'Crude oil sitting in commercial storage, separate from the emergency reserve. This is the working inventory of the oil system - the buffer between production and refining. Compared against the same point in previous years, because stocks build and draw on a seasonal cycle.', null, 'https://www.eia.gov/dnav/pet/pet_stoc_wstk_dcu_nus_w.htm', 'U.S. Energy Information Administration; public domain.', 40),

  ('distillate_stocks', 'Distillate Stocks', 'physical_resource', 'eia', 'petroleum/stoc/wstk:WDISTUS1', 'thousand bbl', 'weekly', false, 'level', false, true, 14, 'How much diesel and heating oil is in storage nationally. Low stocks mean no buffer against a cold snap or a refinery going offline. Compared against the same time of year, since these deliberately build before winter and draw down through it.', null, 'https://www.eia.gov/dnav/pet/pet_stoc_wstk_dcu_nus_w.htm', 'U.S. Energy Information Administration; public domain.', 50),

  ('mauna_loa_co2', 'Atmospheric CO2', 'physical_resource', 'noaa', 'mlo_co2_monthly', 'ppm', 'monthly', true, 'level', false, false, 60, 'The concentration of carbon dioxide in the atmosphere, measured continuously on a Hawaiian volcano since 1958 - far from cities, so it reflects the whole planet rather than local pollution. It is the cleanest long-run record we have of how the atmosphere is changing.', 'Rises nearly monotonically, so it sits near the top of its own range almost permanently. That is the correct reading, not a fault.', 'https://gml.noaa.gov/ccgg/trends/', 'NOAA Global Monitoring Laboratory; public domain, attribution requested.', 60),

  ('arctic_sea_ice', 'Arctic Sea Ice Extent', 'physical_resource', 'noaa', 'nsidc_arctic_extent', 'million km2', 'daily', false, 'level', false, true, 10, 'How much of the Arctic Ocean is covered by ice. Ice melts and refreezes every year, so this is compared against the same date in previous years - what matters is whether there is less of it than there used to be at this point in the calendar, not that it is lower in September than in March.', null, 'https://nsidc.org/data/seaice_index', 'National Snow and Ice Data Center; free to use with attribution.', 70),

  ('lake_mead_storage', 'Lake Mead Storage', 'physical_resource', 'usbr', '921/17', 'acre-feet', 'daily', false, 'level', false, true, 12, 'How much water is held in Lake Mead, the largest reservoir on the Colorado River. It supplies drinking water, farmland and hydroelectric power across the American Southwest. Compared against the same time of year, since reservoirs fill and drain seasonally.', null, 'https://www.usbr.gov/uc/water/hydrodata/', 'U.S. Bureau of Reclamation; public domain.', 80),

  ('lake_powell_storage', 'Lake Powell Storage', 'physical_resource', 'usbr', '919/17', 'acre-feet', 'daily', false, 'level', false, true, 12, 'Water held in Lake Powell, the other major Colorado River reservoir and the one upstream of Lake Mead. Watch the two together: when both fall at once, the whole river system is short rather than the water simply having moved downstream.', null, 'https://www.usbr.gov/uc/water/hydrodata/', 'U.S. Bureau of Reclamation; public domain.', 90),

  ('food_price_index', 'FAO Food Price Index', 'physical_resource', 'fao', 'Food Price Index', 'index 2014-16=100', 'monthly', true, 'level', false, false, 50, 'A basket price for the food commodities traded internationally - cereals, vegetable oils, dairy, meat and sugar - tracked monthly by the UN. Sharp rises in this index have repeatedly preceded political unrest in countries that import most of their food.', null, 'https://www.fao.org/worldfoodsituation/foodpricesindex/en/', 'FAO; free to use with attribution.', 100),

  ('chokepoint_hormuz', 'Strait of Hormuz Transits', 'supply_conflict', 'portwatch', 'Strait of Hormuz', 'ships/day', 'daily', false, 'level', false, false, 12, 'The number of ships passing through the Strait of Hormuz each day. Roughly a fifth of the world''s oil moves through this narrow channel between Iran and Oman, and there is no alternative route for most of it. Fewer ships means trade is being disrupted.', null, 'https://portwatch.imf.org/', 'IMF PortWatch; open data.', 10),

  ('chokepoint_suez', 'Suez Canal Transits', 'supply_conflict', 'portwatch', 'Suez Canal', 'ships/day', 'daily', false, 'level', false, false, 12, 'Daily ship transits through the Suez Canal, the shortcut between Europe and Asia. When traffic drops, cargo reroutes around the southern tip of Africa, adding roughly ten days and substantial cost to every affected voyage.', null, 'https://portwatch.imf.org/', 'IMF PortWatch; open data.', 20),

  ('chokepoint_bab_el_mandeb', 'Bab el-Mandeb Transits', 'supply_conflict', 'portwatch', 'Bab el-Mandeb Strait', 'ships/day', 'daily', false, 'level', false, false, 12, 'Daily transits through Bab el-Mandeb, the strait at the mouth of the Red Sea and the southern gate to the Suez route. It is the stretch most exposed to attacks on shipping, so it usually moves before Suez does.', 'Traffic fell sharply in late 2023 and stayed low. Because the score compares against a trailing ten-year window, a disruption that persists for years gradually becomes the new baseline.', 'https://portwatch.imf.org/', 'IMF PortWatch; open data.', 30),

  ('chokepoint_panama', 'Panama Canal Transits', 'supply_conflict', 'portwatch', 'Panama Canal', 'ships/day', 'daily', false, 'level', false, false, 12, 'Daily ship transits through the Panama Canal. Unlike the other chokepoints this one is limited by fresh water: the canal lifts ships over a mountain range using lake water, so a drought directly reduces how many vessels can cross.', null, 'https://portwatch.imf.org/', 'IMF PortWatch; open data.', 40)
on conflict (slug) do update set
  name = excluded.name,
  failure_mode = excluded.failure_mode,
  source = excluded.source,
  source_series_id = excluded.source_series_id,
  unit = excluded.unit,
  cadence = excluded.cadence,
  higher_is_worse = excluded.higher_is_worse,
  transform = excluded.transform,
  is_counter = excluded.is_counter,
  seasonal = excluded.seasonal,
  stale_after_days = excluded.stale_after_days,
  explainer = excluded.explainer,
  notes = excluded.notes,
  source_url = excluded.source_url,
  license = excluded.license,
  display_order = excluded.display_order;

commit;
